package com.aMu.imageP.domain;

import java.util.Date;

public class ResPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_pic.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_pic.pic_path
     *
     * @mbggenerated
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_pic.pic_size
     *
     * @mbggenerated
     */
    private String picSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_pic.pic_width
     *
     * @mbggenerated
     */
    private String picWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_pic.pic_length
     *
     * @mbggenerated
     */
    private String picLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_pic.pic_type
     *
     * @mbggenerated
     */
    private String picType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_pic.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column res_pic.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_pic.id
     *
     * @return the value of res_pic.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_pic.id
     *
     * @param id the value for res_pic.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_pic.pic_path
     *
     * @return the value of res_pic.pic_path
     *
     * @mbggenerated
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_pic.pic_path
     *
     * @param picPath the value for res_pic.pic_path
     *
     * @mbggenerated
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_pic.pic_size
     *
     * @return the value of res_pic.pic_size
     *
     * @mbggenerated
     */
    public String getPicSize() {
        return picSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_pic.pic_size
     *
     * @param picSize the value for res_pic.pic_size
     *
     * @mbggenerated
     */
    public void setPicSize(String picSize) {
        this.picSize = picSize == null ? null : picSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_pic.pic_width
     *
     * @return the value of res_pic.pic_width
     *
     * @mbggenerated
     */
    public String getPicWidth() {
        return picWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_pic.pic_width
     *
     * @param picWidth the value for res_pic.pic_width
     *
     * @mbggenerated
     */
    public void setPicWidth(String picWidth) {
        this.picWidth = picWidth == null ? null : picWidth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_pic.pic_length
     *
     * @return the value of res_pic.pic_length
     *
     * @mbggenerated
     */
    public String getPicLength() {
        return picLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_pic.pic_length
     *
     * @param picLength the value for res_pic.pic_length
     *
     * @mbggenerated
     */
    public void setPicLength(String picLength) {
        this.picLength = picLength == null ? null : picLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_pic.pic_type
     *
     * @return the value of res_pic.pic_type
     *
     * @mbggenerated
     */
    public String getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_pic.pic_type
     *
     * @param picType the value for res_pic.pic_type
     *
     * @mbggenerated
     */
    public void setPicType(String picType) {
        this.picType = picType == null ? null : picType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_pic.gmt_create
     *
     * @return the value of res_pic.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_pic.gmt_create
     *
     * @param gmtCreate the value for res_pic.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column res_pic.is_deleted
     *
     * @return the value of res_pic.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column res_pic.is_deleted
     *
     * @param isDeleted the value for res_pic.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}