package com.aMu.imageP.domain;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class SysResTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_template.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_template.template_name
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_template.pic_id
     *
     * @mbggenerated
     */
    private Long picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_template.usage_amount
     *
     * @mbggenerated
     */
    private Integer usageAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_template.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_res_template.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_template.id
     *
     * @return the value of sys_res_template.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_template.id
     *
     * @param id the value for sys_res_template.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_template.template_name
     *
     * @return the value of sys_res_template.template_name
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_template.template_name
     *
     * @param templateName the value for sys_res_template.template_name
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_template.pic_id
     *
     * @return the value of sys_res_template.pic_id
     *
     * @mbggenerated
     */
    public Long getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_template.pic_id
     *
     * @param picId the value for sys_res_template.pic_id
     *
     * @mbggenerated
     */
    public void setPicId(Long picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_template.usage_amount
     *
     * @return the value of sys_res_template.usage_amount
     *
     * @mbggenerated
     */
    public Integer getUsageAmount() {
        return usageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_template.usage_amount
     *
     * @param usageAmount the value for sys_res_template.usage_amount
     *
     * @mbggenerated
     */
    public void setUsageAmount(Integer usageAmount) {
        this.usageAmount = usageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_template.gmt_create
     *
     * @return the value of sys_res_template.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_template.gmt_create
     *
     * @param gmtCreate the value for sys_res_template.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_res_template.is_deleted
     *
     * @return the value of sys_res_template.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_res_template.is_deleted
     *
     * @param isDeleted the value for sys_res_template.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}