package com.aMu.imageP.domain;

import java.util.Date;

public class UserProduction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_production.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_production.production_code
     *
     * @mbggenerated
     */
    private String productionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_production.pic_id
     *
     * @mbggenerated
     */
    private Long picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_production.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_production.is_deleted
     *
     * @mbggenerated
     */
    private Integer isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_production.id
     *
     * @return the value of user_production.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_production.id
     *
     * @param id the value for user_production.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_production.production_code
     *
     * @return the value of user_production.production_code
     *
     * @mbggenerated
     */
    public String getProductionCode() {
        return productionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_production.production_code
     *
     * @param productionCode the value for user_production.production_code
     *
     * @mbggenerated
     */
    public void setProductionCode(String productionCode) {
        this.productionCode = productionCode == null ? null : productionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_production.pic_id
     *
     * @return the value of user_production.pic_id
     *
     * @mbggenerated
     */
    public Long getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_production.pic_id
     *
     * @param picId the value for user_production.pic_id
     *
     * @mbggenerated
     */
    public void setPicId(Long picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_production.gmt_create
     *
     * @return the value of user_production.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_production.gmt_create
     *
     * @param gmtCreate the value for user_production.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_production.is_deleted
     *
     * @return the value of user_production.is_deleted
     *
     * @mbggenerated
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_production.is_deleted
     *
     * @param isDeleted the value for user_production.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }
}