package com.aMu.imageP.dao;

import com.aMu.imageP.domain.SysLabel;
import com.aMu.imageP.domain.SysLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int countByExample(SysLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int deleteByExample(SysLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int insert(SysLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int insertSelective(SysLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    List<SysLabel> selectByExample(SysLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    SysLabel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysLabel record, @Param("example") SysLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysLabel record, @Param("example") SysLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_label
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysLabel record);
}