package com.aMu.imageP.dao;

import com.aMu.imageP.domain.SysTemplateLabelRel;
import com.aMu.imageP.domain.SysTemplateLabelRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysTemplateLabelRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int countByExample(SysTemplateLabelRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int deleteByExample(SysTemplateLabelRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int insert(SysTemplateLabelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int insertSelective(SysTemplateLabelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    List<SysTemplateLabelRel> selectByExample(SysTemplateLabelRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    SysTemplateLabelRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysTemplateLabelRel record, @Param("example") SysTemplateLabelRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysTemplateLabelRel record, @Param("example") SysTemplateLabelRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysTemplateLabelRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_template_label_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysTemplateLabelRel record);
}